apiVersion: extension/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/Nodejsapp/imagestore:v1
        ports:
        - containerPort: 3000
      